<?php

namespace Container7taHrZM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBaseControllerService extends Dantweb_Ecommwatch_App_EcwWatchKernelTestDebugContainer
{
    /**
     * Gets the public 'Dantweb\Ecommwatch\App\Controller\BaseController' shared autowired service.
     *
     * @return \Dantweb\Ecommwatch\App\Controller\BaseController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/App/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/App/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Framework/Service/ModelResolver.php';
        include_once \dirname(__DIR__, 4).'/src/Framework/Service/BaseImportService.php';
        include_once \dirname(__DIR__, 4).'/src/Framework/Service/ExpressionResolver.php';

        $container->services['Dantweb\\Ecommwatch\\App\\Controller\\BaseController'] = $instance = new \Dantweb\Ecommwatch\App\Controller\BaseController(($container->services['Dantweb\\Ecommwatch\\Framework\\Service\\ExpressionResolver'] ??= new \Dantweb\Ecommwatch\Framework\Service\ExpressionResolver()), new \Dantweb\Ecommwatch\Framework\Service\ModelResolver(), new \Dantweb\Ecommwatch\Framework\Service\BaseImportService((\dirname(__DIR__, 3).'/import_data')));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'router' => ['services', 'router', 'getRouterService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'router' => '?',
            'request_stack' => '?',
            'http_kernel' => '?',
            'parameter_bag' => '?',
        ]))->withContext('Dantweb\\Ecommwatch\\App\\Controller\\BaseController', $container));

        return $instance;
    }
}
