<?php

namespace Container7taHrZM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpressionResolverService extends Dantweb_Ecommwatch_App_EcwWatchKernelTestDebugContainer
{
    /**
     * Gets the public 'Dantweb\Ecommwatch\Framework\Service\ExpressionResolver' shared autowired service.
     *
     * @return \Dantweb\Ecommwatch\Framework\Service\ExpressionResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Framework/Service/ExpressionResolver.php';

        return $container->services['Dantweb\\Ecommwatch\\Framework\\Service\\ExpressionResolver'] = new \Dantweb\Ecommwatch\Framework\Service\ExpressionResolver();
    }
}
