<?php

namespace Container7taHrZM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMigratePluginCommandService extends Dantweb_Ecommwatch_App_EcwWatchKernelTestDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.Dantweb\Ecommwatch\App\Command\MigratePluginCommand' shared autowired service.
     *
     * @return \Dantweb\Ecommwatch\App\Command\MigratePluginCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/App/Command/MigratePluginCommand.php';

        return $container->services['console.command.public_alias.Dantweb\\Ecommwatch\\App\\Command\\MigratePluginCommand'] = new \Dantweb\Ecommwatch\App\Command\MigratePluginCommand();
    }
}
