<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7taHrZM\Dantweb_Ecommwatch_App_EcwWatchKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7taHrZM/Dantweb_Ecommwatch_App_EcwWatchKernelTestDebugContainer.php') {
    touch(__DIR__.'/Container7taHrZM.legacy');

    return;
}

if (!\class_exists(Dantweb_Ecommwatch_App_EcwWatchKernelTestDebugContainer::class, false)) {
    \class_alias(\Container7taHrZM\Dantweb_Ecommwatch_App_EcwWatchKernelTestDebugContainer::class, Dantweb_Ecommwatch_App_EcwWatchKernelTestDebugContainer::class, false);
}

return new \Container7taHrZM\Dantweb_Ecommwatch_App_EcwWatchKernelTestDebugContainer([
    'container.build_hash' => '7taHrZM',
    'container.build_id' => '9650a73c',
    'container.build_time' => 1745763260,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container7taHrZM');
