<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM1HH9PQ\Dantweb_Ecommwatch_App_EcwWatchKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM1HH9PQ/Dantweb_Ecommwatch_App_EcwWatchKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerM1HH9PQ.legacy');

    return;
}

if (!\class_exists(Dantweb_Ecommwatch_App_EcwWatchKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerM1HH9PQ\Dantweb_Ecommwatch_App_EcwWatchKernelTestDebugContainer::class, Dantweb_Ecommwatch_App_EcwWatchKernelTestDebugContainer::class, false);
}

return new \ContainerM1HH9PQ\Dantweb_Ecommwatch_App_EcwWatchKernelTestDebugContainer([
    'container.build_hash' => 'M1HH9PQ',
    'container.build_id' => '601280fe',
    'container.build_time' => 1750171767,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM1HH9PQ');
